# Generated by Django 3.2.5 on 2021-07-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='author',
        ),
    ]
